### ISSUE TITLE
Typescript easy of use

### ISSUE THREAD

**Issue by KnisterPeter** [redux-bootstrap/redux-bootstrap#6]
To ease the typescript usage with redux-bootstrap put an index.d.ts in the root of your package which imports 'type_definitions/redux-bootstrap/redux-bootstrap.d.ts'.
Then users do not even need to define the `/// <referen...`

**Comment by remojansen** [comment]
I'm not sure about being able to do that because my type definitions [have some dependencies](https://github.com/remojansen/redux-bootstrap/blob/master/type_definitions/redux-bootstrap/redux-bootstrap.d.ts#L6-L7).

**Comment by KnisterPeter** [comment]
As you can see in one of my projects here (https://github.com/KnisterPeter/pretend) it is possible.

**Comment by remojansen** [comment]
I think that works for you because you publish TypeScript source files but when this project is published to npm the typescript files are actually not published. We publish the compiled javascript and the type definitions only.

The [TypeScript docs](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) explain the requirements:

> Your definition files should
> - be.d.ts files
> - be written as external modules
> - not contain triple-slash references

The type definitions contain triple-slash references so we need people to manually reference the `.d.ts` file:

    /// <reference path="node_modules/redux-bootstrap/type_definitions/redux-bootstrap/redux-bootstrap.d.ts" />

Microsoft is working on a new way to publics type definitions via npm for TypeScript 2.0 so I will wait for that to be announced and do it the way they recommend.

**Comment by remojansen** [comment]
Added dts files to npm module and will be released in 1.0.1
