### ISSUE TITLE
example failing

### ISSUE THREAD

**Issue by veeramarni** [redux-bootstrap/redux-bootstrap#85]
## Steps to Reproduce (for bugs)

1. Do a fresh install and try to start the app

## Context
Trying to start the example project using redux-bootstrap
## Your Environment
* Version used: latest

# Stack trace

ERROR in [at-loader] ./node_modules/redux-bootstrap/dts/interfaces/interfaces.d.ts:21:35
    TS2694: Namespace '"/Users/x/Documents/eclipse/workspace/phoneapps/development/examples/redux-bootstrap-example/node_modules/@types/react-router-redux/index"' has no exported member 'ReactRouterReduxHistory'.

**Comment by remojansen** [comment]
Hi, Sorry I think this is an issue caused by the latest version of the react-router and related packages...

I documented the change https://github.com/redux-bootstrap/redux-bootstrap/commit/521c1e4c8789d852c8fb4b0f4882ad3a94bdb561

I need to revisit the example to make sure it works as well. Please feel free to send a PR if you fix it. If now I will fix it when I have some time but please note that it may take a long time...

**Comment by remojansen** [comment]
Based on your PR this issue can be closed right?

**Comment by veeramarni** [comment]
Please review the PR #86 which fixes this issue.

**Comment by remojansen** [comment]
I will try to do a release this evening :)
